### ISSUE TITLE
Representation of OCL constraints

### ISSUE THREAD

**Issue by jechterhoff** [inspire-eu-rdf/inspire-rdf-guidelines#20]
## Description

The ISO/DIS 19150-2 schema conversion rule maps constraints from the UML model. It does not specify how exactly – so there is room for interpretation. Including OCL in the RDF vocabulary is questionable. 

We propose to include only the documentation of an OCL constraint. 

However, there is one exception: OCL constraints in subtypes that restrict the type of a property inherited from a supertype. This requires further consideration.

**Comment by jechterhoff** [comment]
To restrict the values of a property (that in the UML model is inherited from a supertype) to individuals that are instances of a particular class, OWL universal quantifications could be used. However, the validation of these quantifications requires OWL reasoning capabilities. While such tools exist, it is unclear if the basic INSPIRE vocabulary needs to include these expressions. Humans will more easily understand the description of the OCL constraint, if documented in the core vocabulary. The quantifications could - potentially together with other complex class expressions and axioms - become part of additional ontology modules. The pure publication of INSPIRE data in RDF is possible without validation.

The Shapes Constraint Language (SHACL) might be another option to implement the OCL constraint in such a way that it can be validated on RDF data. However, this W3C specification is still a working draft.

**Comment by jechterhoff** [comment]
The current draft vocabularies follow the proposed approach. For further details, see section [Constraint ](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/#ref_cr_constraint) of the guidelines.

Regarding SHACL, also see #33.

**Comment by cportele** [comment]
The issue is closed for now, but in case the topic pops up again, http://spinrdf.org/shacl-and-owl.html might be useful information.
