### ISSUE TITLE
INSPIRE spatial object type classification

### ISSUE THREAD

**Issue by jechterhoff** [inspire-eu-rdf/inspire-rdf-guidelines#25]
## Description

Let us assume that the representation of an INSPIRE feature in INSPIRE RDF schemas was split in two resources: 1) containing information about the real-world phenomenon, and 2) containing information about the feature document itself (feature metadata, see issue #22).

It is not clear which of the subjects would be typed using the feature type classification. I.e., which of the two following statements is correct: 
- :featuredocument    rdf:type        cp:CadastralParcel
- :realworldobject    rdf:type        cp:CadastralParcel
## Discussion Item

Should the real-world phenomenon, the feature document or both be typed with an INSPIRE spatial object type classification?

**Comment by DieterDePaepe** [comment]
I believe the second case is the only correct one, assuming that I interpret "feature type classification" correctly.

You are describing a real world object, that object is a cadastral parcel, hence: `:rwo rdf:type cp:CadastralParcel`.
That real world object might have been measured by a GIS expert, who documented that in his GIS software. That measured object is a `Feature`, but not a `cp:CadastralParcel`.

**Comment by jechterhoff** [comment]
The draft vocabularies do not differentiate between properties that describe the real-world phenomenon and properties that contain feature metadata (see also #22). If that changes in the future, we can re-open this issue.
