### ISSUE TITLE
Representation of aggregation and composition relationships

### ISSUE THREAD

**Issue by jechterhoff** [inspire-eu-rdf/inspire-rdf-guidelines#27]
## Description

ISO 19150-2 specifies an approach to represent UML aggregation and composition relationships in RDF. There, a UML association role that is playing the parts of an aggregation or composition association is represented in RDF via an annotation property (iso19150-2:aggregationType with a value of “partOfSharedAggregation” or “partOfCompositeAggregation”).

We believe that the distinction of aggregation and composition adds no value when publishing RDF data, especially when considering the open world assumption.

**Comment by DieterDePaepe** [comment]
Additionally, the URIs for the ISO19150-2 terms result in a 404.

**Comment by cportele** [comment]
@DieterDePaepe Indeed, I have created an issue in the repository where the ISO/TC 211 ontologies are maintained: https://github.com/ISO-TC211/GOM/issues/4

@jechterhoff I noticed that Jean has changed the 19150-2 base URI three months ago... It now is http://def.isotc211.org/iso19150/-2/2012/base. This raises the question how stable/reliable that ontology is.

**Comment by jechterhoff** [comment]
The encoding rule defined in the guidelines does not convert aggregation and composition.

The base URI of ISO 19150-2 has been fixed (though it's still unresolvable).
