### ISSUE TITLE
Incorrect use of lcn:geographicName?

### ISSUE THREAD

**Issue by DieterDePaepe** [inspire-eu-rdf/inspire-rdf-guidelines#29]
Section 9.3.1 of the [draft guidelines](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/#ref_cr_mappings_inspireGeographicalNames) states:

> It is required that properties with INSPIRE GeographicalName as value type are aligned with the ISA Programme Location Core Vocabulary property "geographicName".

This is demonstrated in eg:

```
ad:AddressRepresentation.postName
        a                   owl:ObjectProperty ;
        rdfs:domain         ad:AddressRepresentation ;
        rdfs:range          ad:GeographicalName ;
        rdfs:subPropertyOf  locn:geographicName ;
```

However, `locn:geographicName` is defined as "[...] a proper noun applied to a spatial object."

This seems to imply that `AddressRepresentation` can be seen as a spatial object. This contradicts its definition: "Representation of an address spatial object for...". It is a representation of a spatial object, not an actual spatial object.

Context of this remark: the Flemish government is finishing a similar exercise ([OSLO²](https://informatievlaanderen.github.io/OSLO/)) to model their models in RDF while complying to INSPIRE. In this exercise we saw incompatibilities between INSPIRE and locn.

**Comment by jechterhoff** [comment]
It's a matter of context, I think. If locn:geographicName is used to describe an AddressRepresentation, then the noun conveyed by locn:geographicName applies to the address spatial object that is represented by ad:AddressRepresentation.

The definition of locn:geographic name, especially considering the ontological definition (which does not state an rdfs:domain), does not require that the instance the property applies to must be a spatial object itself. The definition does not prohibit indirection.

The alignment with locn:geographicName (via the predicate rdfs:subPropertyOf) can be seen as a convenience for users: If a user queries RDF data using locn:geographicName, then query engines that support reasoning should be able to return properties from INSPIRE vocabularies that are aligned with locn:geographicName. These properties would keep their specific meaning (as defined in the INSPIRE application schema), but at the same time, through the alignment, also have the meaning of a locn:geographicName (that the property value is a noun applied to a spatial object).

**Comment by cportele** [comment]
@DieterDePaepe - Do you have any more information (preferably in English) about the "incompatibilities between INSPIRE and locn" that you have identified in your work?

Since locn was explicitly designed ["to aid the publication of data that is interoperable with EU INSPIRE Directive"](https://www.w3.org/ns/locn) this would be useful to understand. 

@michellutz @andrea-perego - for information.

**Comment by DieterDePaepe** [comment]
> It's a matter of context, I think. If locn:geographicName is used to describe an AddressRepresentation, then the noun conveyed by locn:geographicName applies to the address spatial object that is represented by ad:AddressRepresentation.
> 
> The definition of locn:geographic name, especially considering the ontological definition (which does not state an rdfs:domain), does not require that the instance the property applies to must be a spatial object itself. The definition does not prohibit indirection.

I see your point, but I don't think it is correct to interpret it that way. [The RDF specification](https://www.w3.org/TR/rdf11-concepts/) states that a predicate "[...] holds between the resources denoted by the subject and object.". Maybe `locn:geographicName` was intended to be used the way you use it, but the current definition is not flexible enough in my eyes. A different definition that clearly states indirection is `locn:locatorName`:
> Proper noun(s) applied to the real world entity identified by the locator. [...]

---

> Do you have any more information (preferably in English) about the "incompatibilities between INSPIRE and locn" that you have identified in your work?

I was mainly referring to the use of `locn:geographicName`. We found `locn:geographicName` to be unsuited for the reasons listed above.

Another incompatibility came mainly from the difference in dealing with representation between the Geo and RDF world. The Geo world makes a distinction between a _spatial thing_ (a real world object) and a _spatial object_ (its representation), see [Inspire D2.5, section H4.1](http://inspire.ec.europa.eu/documents/Data_Specifications/D2.5_v3.4.pdf) for some examples. People unfamiliar with the terms, such as a lot of RDF people will treat these terms as equivalent, while INSPIRE seems to demand the distinction.

As an example (taken from D2.5), Geo people will say a monitoring facility with identifier X has an abstraction Y with inspireId Y', and say Y has purpose Z. RDF people will say X has purpose Z, not being sure where Y' belongs.

Lastly, the distinction that INSPIRE makes between an Address and an AddressRepresentation has a bit of a mismatch with the single class `locn:Address` (which maps onto AddressRepresentation). Besides the naming, there are no actual semantic conflicts here because locn defines `locn:address` without a domain. (Something they probably did for INSPIRE compatiblity, but unfortunately resulting in a very vague term.)
The differentiation does not look necessary in my eyes, besides the INSPIRE model requiring it.

**Comment by jechterhoff** [comment]
The definition of locn:geographicName needs to be clarified (is indirection allowed or not).

In the meantime, we could change the requirement REQ/OWL/property/alignment/locn/geographicName into a permission: _A property that is encoded as an OWL property, and has INSPIRE GeographicalName as value type may be an rdfs:subPropertyOf the ISA Programme Location Core Vocabulary property "geographicName"_. 

Alternatively, we can restrict the requirement to properties that belong to spatial object types / feature types. That would avoid the potential conflict we have with properties from AddressRepresentation (and maybe other data types).

**Comment by DieterDePaepe** [comment]
The second option has my preference, though there seems to be some confusion as to what a "spatial object/feature" exactly is: #31.

**Comment by jechterhoff** [comment]
Good. Let's wait if there's further feedback on this point (specifically: locn:geographicName). If there's no further discussion, we can realize the second option.

**Comment by andrea-perego** [comment]
@DieterDePaepe , @jechterhoff , just a clarification about locn:geographicName, and the "indirection" issue.

The wording of the informal definition of that property ("a proper noun applied to a spatial object"), and the fact that, [in the LOCN diagram](https://www.w3.org/ns/locn#glance), it is shown as a property of dct:Location is reflecting the use cases identified during the design of the vocabulary.

However, no domain or range has been associated with locn:geographicName exactly in view of not considered use cases. Formally, locn:geographicName can be used on any resource (rdfs:Resource).

About the distinction between AddressRepresentation (data type) and Address (feature type) in INSPIRE, one of the questions is whether this is really relevant / useful in the RDF representation - or, at least, so important to require the definition of new properties / classes, instead of re-using existing ones.

More in general, I think there's a key point to consider. One of the reasons of representing INSPIRE data in RDF is to facilitate their re-use in other sectors. So, the design choices need to be assessed also against this requirement, to understand how they can impact on data re-use.

**Comment by DieterDePaepe** [comment]
I'm aware that `locn:geographicName` lacks a domain and have taken that into account for all my arguments. Despite the lack of a domain, the wording of the definition convinces me that it is only intended to be used on spatial objects which (as a non-geo, non-INSPIRE expert) I would interpret - due to the lack of a clear included definition - as something that has a spatial presence. I.e. a real world object.

> About the distinction between AddressRepresentation (data type) and Address (feature type) in INSPIRE, one of the questions is whether this is really relevant / useful in the RDF representation - or, at least, so important to require the definition of new properties / classes, instead of re-using existing ones.

Term re-use is great, as long as the definitions are respected. Automated data clients have to be sure they are consuming exactly what they expect according to their descriptions. Mixing terms because they are similar (but are in fact non-compatible) is a slippery slope back to the problem semantic web is trying to solve.

**Comment by nicky508** [comment]
I noticed this issue as well. As @DieterDePaepe mentioned the difference between geo and address representation this forms a issue in the conversion of Dutch addresses. In the Netherlands (I guess in more countries as well) a address could have extra additions to describe a specific building part, property name or room. This is where the Postname comes in, at least if we use the location core vocab. Geographical names are much wider, recording this address addition as geographical name, it would some spatial thing related to the address. Using postname would mean, it actually part of the address (which it actually is).

**Comment by jechterhoff** [comment]
The alignment with locn:geographicName is now restricted to properties that belong to spatial objects / feature types. The draft [guidelines](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/#ref_cr_prop_alignment_geographicalName) and [vocabularies](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies) have been updated accordingly.
@DieterDePaepe: Can we close this issue now?

**Comment by DieterDePaepe** [comment]
Skimming through the linked guidelines, I noticed that section 9.4.1 seems to say it is allowed to use `rdfs:label` for any property that refers to a GeographicalName, while section 9.4.2 requires that the used property is a subproperty of `locn:geographicName`. I guess this refers to the choice to between using Literals or complex objects, but it should be made more explicit I think.

Besides this, I think section 10.3 clears up my initial issue, so this can be closed.

**Comment by jechterhoff** [comment]
Thanks you.

This issue can be re-opened in the future, if necessary.
