### ISSUE TITLE
RDF guideliness and data specifications

### ISSUE THREAD

**Issue by nicky508** [inspire-eu-rdf/inspire-rdf-guidelines#34]
Currently we have been working on a cadastral dataset.

The RDF guideliness maintain:

"This document specifies an experimental encoding rule for representing spatial data sets in INSPIRE as RDF. The use of RDF is optional and does not supersede or replace the requirements regarding encoding specified in Clause 9 of the Data Specifications. This optional encoding is intended to support the e-government and open data community in Europe, which is increasingly looking at RDF to represent data."

Does this mean that the data still has to comply to the data specifications? If so, a lot of data in the dataset will be lost, because of the compliance which is demanded by the specification. While RDF can be the solution to capture the more rich data in the inspire dataset.

**Comment by jechterhoff** [comment]
As far as I'm concerned, the cadastral information that is covered by the INSPIRE data specifications (like Cadastral Parcels) should be represented as defined by the INSPIRE RDF guidelines and draft vocabularies. 

For example, if the dataset contains a cadastral parcel, encode it as a cp:CadastralParcel with applicable properties like cp:CadastralParcel.geometry. 

If your dataset contains more data (than what is covered by the INSPIRE schemas), then you are certainly allowed to add that in any way you see fit

**Comment by jechterhoff** [comment]
Extensions are allowed. We added another [section on this topic](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/#ref_instance_cr_extensions) to the guidelines.
